# Site settings
title: ivanchou's dev life
email: zxlrank@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ivanchou_xl
github_username:  bigsquirrel

# Build settings
markdown: kramdown
