markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title.html
name: "金木不缺水 he 土"
markdown: kramdown

author: "ivanchou"
disqus: "ivanchou_xl"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

